# Generated by Django 4.2.16 on 2024-10-27 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Modulname')),
                ('short_name', models.CharField(max_length=20, verbose_name='Kurzname')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_level', models.CharField(max_length=50, verbose_name='Service Level')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Letzter Login')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('priority', models.IntegerField(verbose_name='Priorität')),
                ('status', models.CharField(choices=[('Received', 'Eingegangen'), ('IN_PROGRESS', 'In Bearbeitung'), ('QUESTION_OPEN', 'Frage offen'), ('QUESTION_ANSWERED', 'Frage beantwortet'), ('FORWARDED', 'Weitergeleitet'), ('CLOSED', 'Geschlossen')], default='Received', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Erstellt von')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Prüfer')),
                ('module', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Koma.module', verbose_name='Modul')),
            ],
            options={
                'permissions': [('can_view_tickets', 'Can view tickets'), ('can_view_users', 'Can view users')],
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True, verbose_name='Benutzername')),
                ('password', models.CharField(max_length=128, verbose_name='Passwort')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
        ),
        migrations.CreateModel(
            name='ChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_old', models.TextField(blank=True, null=True, verbose_name='Alter Text')),
                ('text_new', models.TextField(blank=True, null=True, verbose_name='Neuer Text')),
                ('state_old', models.CharField(blank=True, choices=[('Received', 'Eingegangen'), ('IN_PROGRESS', 'In Bearbeitung'), ('QUESTION_OPEN', 'Frage offen'), ('QUESTION_ANSWERED', 'Frage beantwortet'), ('FORWARDED', 'Weitergeleitet'), ('CLOSED', 'Geschlossen')], max_length=20, null=True, verbose_name='Alter Status')),
                ('state_new', models.CharField(blank=True, choices=[('Received', 'Eingegangen'), ('IN_PROGRESS', 'In Bearbeitung'), ('QUESTION_OPEN', 'Frage offen'), ('QUESTION_ANSWERED', 'Frage beantwortet'), ('FORWARDED', 'Weitergeleitet'), ('CLOSED', 'Geschlossen')], max_length=20, null=True, verbose_name='Neuer Status')),
                ('change_date', models.DateTimeField(auto_now_add=True, verbose_name='Änderungsdatum')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Geändert von')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='Koma.ticket', verbose_name='Ticket')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Koma.module', verbose_name='Modul')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Benutzer')),
            ],
            options={
                'unique_together': {('module', 'user')},
            },
        ),
    ]
