# Generated by Django 4.2.16 on 2024-10-29 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Koma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketHistory',
            fields=[
                ('change_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Text')),
                ('status', models.CharField(choices=[('Received', 'Eingegangen'), ('IN_PROGRESS', 'In Bearbeitung'), ('QUESTION_OPEN', 'Frage offen'), ('QUESTION_ANSWERED', 'Frage beantwortet'), ('FORWARDED', 'Weitergeleitet'), ('CLOSED', 'Geschlossen')], max_length=20, verbose_name='Status')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Änderungsdatum')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='Koma.ticket', verbose_name='Ticket')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Geändert von')),
            ],
            options={
                'verbose_name_plural': 'Ticket Histories',
            },
        ),
        migrations.DeleteModel(
            name='ChangeHistory',
        ),
    ]
